### ISSUE TITLE
Swift 4.2 update?

### ISSUE THREAD

**Issue by 22Round** [mw99/DataCompression#11]
any plans to update lib to  Swift 4.2

**Comment by mw99** [comment]
The last version should run fine with Swift 4.2. Any problems?

(Swift 5.0 will generate some warnings and will get an update soon)

**Comment by mw99** [comment]
Anyway, I bumped the Swift version in the podspec file to 4.2 and made a new release. 

https://github.com/mw99/DataCompression/releases/tag/3.1.0
