### ISSUE TITLE
Swift 5

### ISSUE THREAD

**Issue by oskarirauta** [mw99/DataCompression#13]
Awful lot of warnings about deprecated uses of withUnsafeBytes..

**Comment by mw99** [comment]
With every new Swift version comes joy. Will take a look...

**Comment by oskarirauta** [comment]
Been there… Thanks.

**Comment by mw99** [comment]
Should be fixed in version 3.4.0
https://github.com/mw99/DataCompression/releases/tag/3.4.0

**Comment by mw99** [comment]
Should be fixed in 3.4.0 https://github.com/mw99/DataCompression/releases/tag/3.4.0

**Comment by oskarirauta** [comment]
Thanks. I can verify that warnings are gone now.
