### ISSUE TITLE
Can't unarchive .zip

### ISSUE THREAD

**Issue by EugeneKudr** [mw99/DataCompression#25]
I try to unzip my .zip file (downloaded from the Internet) using the .unzip () command and get a nil. Also I cannot open on my computer the file zipped by .zip(). With gzip all ok.  Please help!

**Comment by EugeneKudr** [comment]
I  seem to have figured out that this solution is not suitable for pkzip files, but I need to process this type of file. What can I do?

**Comment by mw99** [comment]
Hi. Your best bet ist called ‘minizip’. Maybe google that together with swift and you should find what you are looking for. Good luck.
