### ISSUE TITLE
Swift 5.7 Runtime error in withMemoryRebound

### ISSUE THREAD

**Issue by bentumbler** [mw99/DataCompression#30]
I have been using this library until now but it will no longer run under Swift 5.7 because .withMemoryRebound has been updated.
https://github.com/apple/swift-evolution/blob/main/proposals/0333-with-memory-rebound.md

It would be great to get an update to be Swift 5.7 compatible.

Thanks

**Comment by mw99** [comment]
Thanks for the information. I haven't noticed it until yet. Will push a fix in the next days.

**Comment by mw99** [comment]
Hi again. Should be fixed with [release 3.7.0](https://github.com/mw99/DataCompression/releases/tag/3.7.0).
