### ISSUE TITLE
Is it possible to do gzip() a file with a password? If so, how please?

### ISSUE THREAD

**Issue by waelsaad** [mw99/DataCompression#34]
I would like to zip and unzip my files with a password if possible, I am not sure ! Thanks.

```
				if let compressedData = html.data.gzip() {
					try compressedData.write(to: filePath)
				}
```

**Comment by mw99** [comment]
Encryption is not supported by this library. But it is of course possible to add encryption after compression.
Maybe you can find what you need here:
https://developer.apple.com/documentation/cryptokit/performing_common_cryptographic_operations

Just for info, compression should be performed before encryption. If not, the high entropy of encrypted data streams will cause a very poor compression rate, regardless of which compression algorithm you use.
