### ISSUE TITLE
Missing info in the license file

### ISSUE THREAD

**Issue by omidontop** [mw99/DataCompression#8]
The following line in the license file should be filled by the copyright owner:

 `Copyright {yyyy} {name of copyright owner`

**Comment by mw99** [comment]
No. It's only an example appendix you would copy into other files. While doing so, you would insert your copyright information. Like in [src file](https://github.com/mw99/DataCompression/blob/master/Sources/DataCompression.swift)

**Comment by omidontop** [comment]
@mw99 I disagree. Look at this one as a reference: 

https://github.com/airbnb/lottie-ios/blob/master/LICENSE

And also, CocoaPods uses these LICENSE files to automatically generate an acknowledgement markdown document which can be used in the credits page of the app. Look at: 'Pods/Target Support Files/Pods-Target/Pods-Target-acknowledgements.markdown'.

**Comment by mw99** [comment]
Well... I'm sorry... but you, Airbnb and CocoaPods are all wrong^^

First, it's an **Appendix**,  you may look that up. 

Second, it's clearly says in the license what to do:

>   APPENDIX: How to apply the Apache License to your work.
      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "{}"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

I mean, in case you are right, it would say something like: "Enter your copyright information down below". But it does not.

And third, let's take a look at how Apache web server uses it. They came up with the license, so they should know best right?  https://github.com/apache/httpd/blob/trunk/LICENSE

However, if you can get the Apache guys to change it, I promise I will as well. 😊
